// config.h

#pragma once

#define CONFIG_IF_NAME_SIZE 16
#define CONFIG_GRAPH_NAME_SIZE 32
#define CONFIG_NODE_NAME_SIZE 16
#define CONFIG_MAX_INTF_PER_NODE 10

#define CONFIG_MAX_PACKET_BUFFER_SIZE   2048
